server {
    listen 80;
    server_name api.example.com;
    location / {
        include snippets/proxy-common.conf;
        proxy_ssl_server_name on;
        proxy_ssl_name api.internal.example.com;
        proxy_ssl_verify on;
        proxy_ssl_verify_depth 3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        proxy_pass https://192.168.1.10:9000;
    }
}
