server {
    listen 80;
    server_name app2.example.com;
    location / {
        include snippets/proxy-common.conf;
        include snippets/proxy-websocket.conf;
        proxy_pass http://192.168.1.30:3000;
    }
}
